# Generated by Django 3.1.3 on 2020-11-19 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=200, verbose_name='Tên')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=200, verbose_name='Tên')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Mô tả')),
                ('type_vehicle', models.CharField(default='', max_length=50, verbose_name='Loại xe')),
                ('color', models.CharField(default='', max_length=30, verbose_name='Màu sắc')),
                ('cc', models.FloatField(verbose_name='Phân khối')),
                ('price', models.FloatField(verbose_name='Giá')),
                ('image', models.ImageField(upload_to='static/images', verbose_name='Ảnh')),
                ('year', models.CharField(max_length=10, verbose_name='Năm sản xuất')),
                ('origin', models.CharField(max_length=100, verbose_name='Xuất xứ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.category', verbose_name='Nhóm')),
            ],
        ),
    ]
