# Generated by Django 3.1.3 on 2020-11-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=30, verbose_name='Màu sắc'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_vehicle',
            field=models.CharField(max_length=50, verbose_name='Loại xe'),
        ),
    ]
