# Generated by Django 3.1.3 on 2020-11-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='customer_address',
        ),
        migrations.AddField(
            model_name='contact',
            name='customer_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='customer_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='customer_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='customer_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
