# Generated by Django 3.1.3 on 2020-12-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201127_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='order_date',
            new_name='contact_date',
        ),
    ]
