# Generated by Django 3.1.3 on 2021-03-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201201_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tiêu đề')),
                ('image', models.ImageField(upload_to='static/images_news', verbose_name='Ảnh')),
                ('content', models.TextField(verbose_name='Nội dung')),
            ],
        ),
    ]
