# Generated by Django 3.1.3 on 2021-03-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_news_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='Số lượng'),
        ),
    ]
